[consultas]

# Obtener clientes únicos. (Todos los registrados.)
ObtenerClientesPortal = "SELECT DISTINCT(Id) FROM [NexusFuel].[Portal].[ClientUser]"

# Obtener todas las fechas registradas.
ObtenerFechasRegistradas = "SELECT DISTINCT([Fecha]) FROM [Sinergia_Aux].[dbo].[PreciosPemex] ORDER BY [Fecha] ASC"



